<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_agama extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Data_agama_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'data_agama/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'data_agama/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'data_agama/index.html';
            $config['first_url'] = base_url() . 'data_agama/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Data_agama_model->total_rows($q);
        $data_agama = $this->Data_agama_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'data_agama_data' => $data_agama,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('data_agama/data_agama_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Data_agama_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_agama' => $row->id_agama,
		'agama' => $row->agama,
	    );
            $this->load->view('data_agama/data_agama_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('data_agama'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('data_agama/create_action'),
	    'id_agama' => set_value('id_agama'),
	    'agama' => set_value('agama'),
	);
        $this->load->view('data_agama/data_agama_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'agama' => $this->input->post('agama',TRUE),
	    );

            $this->Data_agama_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('data_agama'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Data_agama_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('data_agama/update_action'),
		'id_agama' => set_value('id_agama', $row->id_agama),
		'agama' => set_value('agama', $row->agama),
	    );
            $this->load->view('data_agama/data_agama_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('data_agama'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_agama', TRUE));
        } else {
            $data = array(
		'agama' => $this->input->post('agama',TRUE),
	    );

            $this->Data_agama_model->update($this->input->post('id_agama', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('data_agama'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Data_agama_model->get_by_id($id);

        if ($row) {
            $this->Data_agama_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('data_agama'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('data_agama'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('agama', 'agama', 'trim|required');

	$this->form_validation->set_rules('id_agama', 'id_agama', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Data_agama.php */
/* Location: ./application/controllers/Data_agama.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-15 00:10:47 */
/* http://harviacode.com */