<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_darah extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Data_darah_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'data_darah/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'data_darah/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'data_darah/index.html';
            $config['first_url'] = base_url() . 'data_darah/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Data_darah_model->total_rows($q);
        $data_darah = $this->Data_darah_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'data_darah_data' => $data_darah,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('data_darah/data_darah_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Data_darah_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_darah' => $row->id_darah,
		'golongan_darah' => $row->golongan_darah,
	    );
            $this->load->view('data_darah/data_darah_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('data_darah'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('data_darah/create_action'),
	    'id_darah' => set_value('id_darah'),
	    'golongan_darah' => set_value('golongan_darah'),
	);
        $this->load->view('data_darah/data_darah_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'golongan_darah' => $this->input->post('golongan_darah',TRUE),
	    );

            $this->Data_darah_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('data_darah'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Data_darah_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('data_darah/update_action'),
		'id_darah' => set_value('id_darah', $row->id_darah),
		'golongan_darah' => set_value('golongan_darah', $row->golongan_darah),
	    );
            $this->load->view('data_darah/data_darah_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('data_darah'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_darah', TRUE));
        } else {
            $data = array(
		'golongan_darah' => $this->input->post('golongan_darah',TRUE),
	    );

            $this->Data_darah_model->update($this->input->post('id_darah', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('data_darah'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Data_darah_model->get_by_id($id);

        if ($row) {
            $this->Data_darah_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('data_darah'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('data_darah'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('golongan_darah', 'golongan darah', 'trim|required');

	$this->form_validation->set_rules('id_darah', 'id_darah', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Data_darah.php */
/* Location: ./application/controllers/Data_darah.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-15 00:18:23 */
/* http://harviacode.com */