<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_kis_model extends CI_Model
{

    public $table = 'data_kis';
    public $id = 'id_kis';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kis', $q);
	$this->db->or_like('kode_anak', $q);
	$this->db->or_like('nik_bayi', $q);
	$this->db->or_like('nama_nayi', $q);
	$this->db->or_like('nama_bapak', $q);
	$this->db->or_like('nama_ibu', $q);
	$this->db->or_like('alamat_lengkap', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('photo_anak', $q);
	$this->db->or_like('photo_kk', $q);
	$this->db->or_like('photo_akta_kelahiran', $q);
	$this->db->or_like('photo_ktp_ayah', $q);
	$this->db->or_like('photo_ktp_ibu', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kis', $q);
	$this->db->or_like('kode_anak', $q);
	$this->db->or_like('nik_bayi', $q);
	$this->db->or_like('nama_nayi', $q);
	$this->db->or_like('nama_bapak', $q);
	$this->db->or_like('nama_ibu', $q);
	$this->db->or_like('alamat_lengkap', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('photo_anak', $q);
	$this->db->or_like('photo_kk', $q);
	$this->db->or_like('photo_akta_kelahiran', $q);
	$this->db->or_like('photo_ktp_ayah', $q);
	$this->db->or_like('photo_ktp_ibu', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_kis_model.php */
/* Location: ./application/models/Data_kis_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-07 18:48:56 */
/* http://harviacode.com */